[project]
name = "fastapi_exp"
version = "0.1.0"
description = "FastAPI-based ML inference system"
authors = [
    { name = "kosmobiker", email = "your.email@example.com" }
]
requires-python = ">=3.13"
readme = "README.md"
license = { text = "MIT" }

dependencies = [
    "fastapi>=0.100.0",
    "uvicorn>=0.23.0",
    "sqlalchemy>=2.0.19",
    "alembic>=1.11.1",
    "psycopg2-binary>=2.9.6",
    "pydantic>=2.1.1",
    "pydantic-settings>=2.0.2",
    "xgboost>=1.7.6",
    "newrelic>=8.8.0",
    "python-jose[cryptography]>=3.3.0",
    "passlib[bcrypt]>=1.7.4",
    "python-multipart>=0.0.6",
    "emails>=0.6",
    "numpy>=1.26.0",
    "pandas",
    "scikit-learn"
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
    "pytest-cov>=4.1.0",
    "locust>=2.16.1",
    "ruff>=0.1.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["fastapi_exp"]

[tool.ruff]
target-version = "py313"
line-length = 88
fix = true

select = [
    "E",  # pycodestyle errors
    "F",  # pyflakes
    "B",  # flake8-bugbear
    "UP",  # pyupgrade
    "N",   # pep8-naming
    "I",   # isort
    "RUF", # ruff-specific rules
]
ignore = [
    "E501",  # line too long
]

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"tests/*" = [
    "S101",  # Use of assert detected
]

[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q -v --cov=app --cov-report=term-missing"
testpaths = [
    "tests",
]

[project.urls]
"Homepage" = "https://github.com/kosmobiker/fastapi_exp"
"Bug Tracker" = "https://github.com/kosmobiker/fastapi_exp/issues"
